name: beacon # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Scanning for beacon by Banana-LABS # 79 char long summary
description: |
    Permite scanear beacons desde ubunut-core
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps: 
  beacon:
    command: beacon

parts:
  beaconscan:
    # See 'snapcraft plugins'
    source: https://github.com/eliaguirre/beaconscan.git
    source-tag: v0.3
    plugin: python
